"""
Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V. (MPG) is
holder of all proprietary rights on this computer program.
Using this computer program means that you agree to the terms 
in the LICENSE file included with this software distribution. 
Any use not explicitly granted by the LICENSE is prohibited.

Copyright©2023 Max-Planck-Gesellschaft zur Förderung
der Wissenschaften e.V. (MPG). acting on behalf of its Max Planck Institute
for Intelligent Systems. All rights reserved.

For comments or questions, please email us at tempeh@tue.mpg.de
"""

import os
import random
import imageio
import numpy as np
import cv2

# -----------------------------------------------------------------------------

def get_subset_views(number_views, minimum_views=4):       
    views = np.arange(number_views)
    if minimum_views >= number_views:
        return views

    random.shuffle(views)
    number_selected_views = int(round(minimum_views + (number_views - minimum_views) * np.random.random(), 0))
    return views[:number_selected_views]

# -----------------------------------------------------------------------------

def get_random_crop_offsets(crop_size, height, width):
    if isinstance(crop_size, tuple):
        crop_height = crop_size[0]
        crop_width = crop_size[1]
    else:
        crop_width = crop_height = crop_size

    w_offset = np.random.randint(0, max(1, width - crop_width - 1))
    h_offset = np.random.randint(0, max(1, height - crop_height - 1))
    return h_offset, w_offset

# -----------------------------------------------------------------------------

def pad_width_or_height( data, output_width=256, output_height=256, pad_value=0, return_offsets=False ):
    # pad the image to be at least (output_height, output_width) resolution
    # assume data in shape (h,w,*)
    from PIL import Image
    if isinstance( data, np.ndarray ):
        height, width = data.shape[0], data.shape[1]
        with_channel = len(data.shape) == 3
    elif isinstance( data, Image.Image ):
        height, width = data.height, data.width
        with_channel = len(data.size) == 3

    p_left, p_right, p_top, p_bottom = 0, 0, 0, 0
    if width < output_width:
        p_left  = int( np.floor( ( output_width - width ) / 2 ) )
        p_right = ( output_width - width ) - p_left
    if height < output_height:
        p_top = int( np.floor( ( output_height - height ) / 2 ) )
        p_bottom = ( output_height - height ) - p_top

    if isinstance( data, np.ndarray ):
        if with_channel:
            data = np.pad( data, ( (p_top,p_bottom), (p_left,p_right), (0,0) ), 'constant', constant_values=pad_value )
        else:
            data = np.pad( data, ( (p_top,p_bottom), (p_left,p_right) ), 'constant', constant_values=pad_value )
    elif isinstance( data, Image.Image ):
        import torchvision.transforms as transforms
        data = transforms.Pad( (p_left, p_top, p_right, p_bottom) )( data ) # ( left, top, right, bottom )

    if return_offsets:
        return data, p_top, p_bottom, p_left, p_right
    else:
        return data

# # -----------------------------------------------------------------------------

def crop_img(img, crop_size, h_offset, w_offset):
    '''crop an image
    Args:
        img: np.array or tensor image in shape (H,W,C)
        crop_size: tuple (crop_h, crop_w) or scale (assuming square crop)
        h_offset, w_offset: scalars generated by get_random_crop_offsets()
    Returns:
        cropped image
    '''
    if isinstance(img, np.ndarray):
        dim = img.ndim
    elif torch.is_tensor(img):
        dim = img.ndimension() # instead of img.ndim, pytorch 1.1 compatibility issue 
    else:
        raise RuntimeError(f"invalid image type = {type(img)}")

    if isinstance(crop_size, tuple):
        crop_height = crop_size[0]
        crop_width = crop_size[1]
    else:
        crop_width = crop_height = crop_size

    if dim == 3:
        return img[h_offset: h_offset+crop_height,
                   w_offset: w_offset+crop_width, :]
    elif dim == 2:
        return img[h_offset: h_offset+crop_height,
                   w_offset: w_offset+crop_width]

from skimage.transform import rescale, resize

# -----------------------------------------------------------------------------

# def scale_crop(img, crop_size, h_offset, w_offset, scale_factor, K=None, debug=False, debug_root=None, landmarks=None):
#     '''apply (1) scale and (2) crop (with optionally padding)
#     Args:
#         img: np.array image in shape (H,W,C)
#         crop_size: tuple (crop_h, crop_w) or scale (assuming square crop)
#         h_offset, w_offset: scalars generated by get_crop_offsets()
#         scale_factor: scalar, if > 1.0, then enlarge, else shrink
#         K (optional): intrinsic matrix in np.array (3,3)
#         debug: if True, save intermediate images for debugging
#         landmarks (optional): np.array of shape (N,2) for 2D landmarks
#     Returns:
#         img_aug: result image, should always be in crop_size
#         K_aug (if K provided): result intrinsic
#     '''
#     from skimage.transform import rescale, resize
#     if isinstance(img, np.ndarray):
#         dim = img.ndim
#     else:
#         raise RuntimeError(f"invalid image type = {type(img)}")

#     if isinstance(crop_size, tuple):
#         crop_height = crop_size[0]
#         crop_width = crop_size[1]
#     else:
#         crop_width = crop_height = crop_size

#     # debug
#     if debug:
#         os.makedirs(debug_root, exist_ok=True)
#         if debug_root is None:
#             debug_root = '/home/ICT2000/tli/Dropbox/DenseFaceTracking/debug/image_perturbation_with_intrinsics'

#         if landmarks is not None:
#             for i in range(landmarks.shape[0]):
#                 cv2.circle(img, (int(landmarks[i,0]), int(landmarks[i,1])), 1, (1.0, 0.0, 0.0), -1)

#         imageio.imsave(os.path.join(debug_root, '0_input.png'), (255.*img).astype(np.uint8))

#     # scaling
#     if dim == 3:
#         # img = rescale( img.copy(), scale_factor, multichannel=True, anti_aliasing=True )
#         img = rescale( img.copy(), scale_factor, channel_axis=2, anti_aliasing=True )
#     elif dim == 2:
#         # img = rescale( img.copy(), scale_factor, multichannel=False, anti_aliasing=True )
#         img = rescale( img.copy(), scale_factor, anti_aliasing=True )
#     else:
#         raise RuntimeError(f"invalid input image dimension num = {dim}")

#     if landmarks is not None:
#         # scale landmarks
#         landmarks = landmarks * scale_factor


#     if debug: 
#         vis_img = img.copy()
#         if landmarks is not None:
#             for i in range(landmarks.shape[0]):
#                 cv2.circle(vis_img, (int(landmarks[i,0]), int(landmarks[i,1])), 1, (1.0, 0.0, 0.0), -1)
#         imageio.imsave(os.path.join(debug_root, '1_scaled.png'), (255.*vis_img).astype(np.uint8))

#     # crop
#     img = crop_img(img, crop_size, h_offset, w_offset)
#     if landmarks is not None:
#         landmarks[:,0] = landmarks[:,0] - w_offset
#         landmarks[:,1] = landmarks[:,1] - h_offset


#     if debug: 
#         vis_img = img.copy()
#         if landmarks is not None:
#             for i in range(landmarks.shape[0]):
#                 cv2.circle(vis_img, (int(landmarks[i,0]), int(landmarks[i,1])), 1, (1.0, 0.0, 0.0), -1)
        
#         imageio.imsave(os.path.join(debug_root, '2_cropped.png'), (255.*vis_img).astype(np.uint8))

#     # pad
#     if img.shape[0] < crop_height or img.shape[1] < crop_width:
#         img, p_top, p_bottom, p_left, p_right = pad_width_or_height(
#             img, output_width=crop_width, output_height=crop_height, return_offsets=True) # pad to at least bigger than target size

#         if landmarks is not None:
#             landmarks[:,0] = landmarks[:,0] + p_left
#             landmarks[:,1] = landmarks[:,1] + p_top

#     else:
#         p_top, p_bottom, p_left, p_right = 0., 0., 0., 0.
#     if debug: 
#         vis_img = img.copy()
#         if landmarks is not None:
#             for i in range(landmarks.shape[0]):
#                 cv2.circle(vis_img, (int(landmarks[i,0]), int(landmarks[i,1])), 1, (1.0, 0.0, 0.0), -1)
#         imageio.imsave(os.path.join(debug_root, '3_padded.png'), (255.*vis_img).astype(np.uint8))

#     # adjust intrinsic, if provided
#     if K is not None:
#         Ks = np.eye(3); Ks[0,0] = scale_factor; Ks[1,1] = scale_factor
#         Kc = np.eye(3); Kc[0,2] = -1.0 * float(w_offset); Kc[1,2] = -1.0 * float(h_offset)
#         Kp = np.eye(3); Kp[0,2] = float(p_left); Kp[1,2] = float(p_top)
#         K_aug = Kp.dot( Kc.dot( Ks.dot(K.copy()) ) )

#         if landmarks is not None:
#             return img, K_aug, landmarks

#         return img, K_aug
#     else:
#         if landmarks is not None:
#             return img, landmarks
#         return img


def scale_crop(img,
               crop_size,
               h_offset,
               w_offset,
               scale_factor,
               K=None,
               normals_image=None,
               debug=False,
               debug_root=None,
               landmarks=None,
               depth_map=None):
    '''apply (1) scale and (2) crop (with optionally padding) to both img and normals_image
    Args:
        img: np.array image in shape (H, W, C)
        crop_size: tuple (crop_h, crop_w) or scalar (assuming square crop)
        h_offset, w_offset: scalars generated by get_crop_offsets()
        scale_factor: scalar, if > 1.0, then enlarge; else shrink
        K (optional): intrinsic matrix as np.array (3, 3)
        normals_image (optional): np.array of same spatial dims as img, e.g. (H, W, 3)
        debug: if True, save intermediate images for debugging
        debug_root: directory path for saving debug images
        landmarks (optional): np.array of shape (N, 2) for 2D landmarks
    Returns:
        result: dict with keys:
            'image'          : final cropped/padded img (shape = crop_size)
            'normals_image'  : final cropped/padded normals_image (or None)
            'K'              : updated intrinsic matrix (or None)
            'landmarks'      : updated landmarks (or None)
    '''
    # 0. Helper: ensure debug_root exists
    if debug:
        if debug_root is None:
            debug_root = '/tmp/debug_image_perturbation'
        os.makedirs(debug_root, exist_ok=True)

        # If landmarks exist, draw them on the input image before saving
        img_debug = img.copy()
        if landmarks is not None:
            for i in range(landmarks.shape[0]):
                cv2.circle(img_debug,
                           (int(landmarks[i, 0]), int(landmarks[i, 1])),
                           1, (1.0, 0.0, 0.0), -1)
        imageio.imsave(os.path.join(debug_root, '0_input.png'),
                       (255. * img_debug).astype(np.uint8))

        # If normals_image is provided, save it too
        if normals_image is not None:
            normals_debug = normals_image.copy()
            imageio.imsave(os.path.join(debug_root, '0_normals_input.png'),
                           (255. * normals_debug).astype(np.uint8))

    # 1. Determine crop dimensions
    if isinstance(crop_size, tuple):
        crop_height, crop_width = crop_size
    else:
        crop_height = crop_width = crop_size

    # 2. Scale both img and normals_image
    #    (detect dimensionality for correct usage of rescale)
    if img.ndim == 3:
        img_scaled = rescale(img.copy(),
                             scale_factor,
                             channel_axis=2,
                             anti_aliasing=True)
    elif img.ndim == 2:
        img_scaled = rescale(img.copy(),
                             scale_factor,
                             anti_aliasing=True)
    else:
        raise RuntimeError(f"invalid image dimension: {img.ndim}")

    normals_scaled = None
    if normals_image is not None:
        if normals_image.ndim == 3:
            normals_scaled = rescale(normals_image.copy(),
                                     scale_factor,
                                     channel_axis=2,
                                     anti_aliasing=True)
        elif normals_image.ndim == 2:
            normals_scaled = rescale(normals_image.copy(),
                                     scale_factor,
                                     anti_aliasing=True)
        else:
            raise RuntimeError(f"invalid normals_image dimension: {normals_image.ndim}")

    depth_scaled = None
    if depth_map is not None:
        # depth is a single channel → no channel_axis
        # depth_scaled = rescale(depth_map, scale_factor, anti_aliasing=True)
        depth_scaled = rescale(depth_map, scale_factor, anti_aliasing=False, preserve_range=True, order=0)


    # 3. Scale landmarks
    landmarks_scaled = None
    if landmarks is not None:
        landmarks_scaled = landmarks.copy() * scale_factor

    if debug:
        vis_img = img_scaled.copy()
        if landmarks_scaled is not None:
            for i in range(landmarks_scaled.shape[0]):
                cv2.circle(vis_img,
                           (int(landmarks_scaled[i, 0]), int(landmarks_scaled[i, 1])),
                           1, (1.0, 0.0, 0.0), -1)
        imageio.imsave(os.path.join(debug_root, '1_scaled.png'),
                       (255. * vis_img).astype(np.uint8))

        if normals_scaled is not None:
            imageio.imsave(os.path.join(debug_root, '1_normals_scaled.png'),
                           (255. * normals_scaled).astype(np.uint8))

    # 4. Crop both img_scaled and normals_scaled
    img_cropped = crop_img(img_scaled, crop_size, h_offset, w_offset)
    normals_cropped = None
    if normals_scaled is not None:
        normals_cropped = crop_img(normals_scaled, crop_size, h_offset, w_offset)

    depth_cropped   = crop_img(depth_scaled,     crop_size, h_offset, w_offset) \
                      if depth_scaled   is not None else None



    # 5. Adjust landmarks after crop
    if landmarks_scaled is not None:
        landmarks_scaled[:, 0] -= w_offset
        landmarks_scaled[:, 1] -= h_offset

    if debug:
        vis_img = img_cropped.copy()
        if landmarks_scaled is not None:
            for i in range(landmarks_scaled.shape[0]):
                cv2.circle(vis_img,
                           (int(landmarks_scaled[i, 0]), int(landmarks_scaled[i, 1])),
                           1, (1.0, 0.0, 0.0), -1)
        imageio.imsave(os.path.join(debug_root, '2_cropped.png'),
                       (255. * vis_img).astype(np.uint8))

        if normals_cropped is not None:
            imageio.imsave(os.path.join(debug_root, '2_normals_cropped.png'),
                           (255. * normals_cropped).astype(np.uint8))

    # 6. Pad if needed to reach (crop_height, crop_width)
    p_top = p_bottom = p_left = p_right = 0
    final_img = img_cropped
    final_normals = normals_cropped
    final_depth = depth_cropped

    if (img_cropped.shape[0] < crop_height) or (img_cropped.shape[1] < crop_width):
        # Pad image
        final_img, p_top, p_bottom, p_left, p_right = pad_width_or_height(
            img_cropped,
            output_width=crop_width,
            output_height=crop_height,
            return_offsets=True
        )

        # Pad normals_image in the same way (if present)
        if normals_cropped is not None:
            # We expect normals_cropped.shape == img_cropped.shape
            # So calling pad_width_or_height on normals_cropped yields same offsets
            final_normals, pt_n, pb_n, pl_n, pr_n = pad_width_or_height(
                normals_cropped,
                output_width=crop_width,
                output_height=crop_height,
                return_offsets=True
            )
            # Optionally, assert that offsets match:
            assert (pt_n == p_top and pb_n == p_bottom and
                    pl_n == p_left and pr_n == p_right), \
                "Padding offsets differ between img and normals_image!"

        if depth_cropped is not None:
            final_depth, pt_d, pb_d, pl_d, pr_d = pad_width_or_height(
                depth_cropped,
                output_width=crop_width,
                output_height=crop_height,
                return_offsets=True
            )


        # Adjust landmarks for padding
        if landmarks_scaled is not None:
            landmarks_scaled[:, 0] += p_left
            landmarks_scaled[:, 1] += p_top
    else:
        final_img = img_cropped
        final_normals = normals_cropped
        final_depth = depth_cropped

    if debug:
        vis_img = final_img.copy()
        if landmarks_scaled is not None:
            for i in range(landmarks_scaled.shape[0]):
                cv2.circle(vis_img,
                           (int(landmarks_scaled[i, 0]), int(landmarks_scaled[i, 1])),
                           1, (1.0, 0.0, 0.0), -1)
        imageio.imsave(os.path.join(debug_root, '3_padded.png'),
                       (255. * vis_img).astype(np.uint8))

        if final_normals is not None:
            imageio.imsave(os.path.join(debug_root, '3_normals_padded.png'),
                           (255. * final_normals).astype(np.uint8))

    # 7. Adjust intrinsic matrix K if provided
    K_aug = None
    if K is not None:
        Ks = np.eye(3)
        Ks[0, 0] = scale_factor
        Ks[1, 1] = scale_factor

        Kc = np.eye(3)
        Kc[0, 2] = -1.0 * float(w_offset)
        Kc[1, 2] = -1.0 * float(h_offset)

        Kp = np.eye(3)
        Kp[0, 2] = float(p_left)
        Kp[1, 2] = float(p_top)

        K_aug = Kp.dot(Kc.dot(Ks.dot(K.copy())))

    # 8. Build the result dictionary
    result = {
        'image': final_img,
        'normals_image': final_normals,
        'K':      K_aug,
        'landmarks': landmarks_scaled,
        'depth_map'    : final_depth,   # ← NEW
    }
    return result



def pad_img_and_intrinsics(img_cropped,
               K=None,
               normals_cropped=None,
               landmarks=None,
               depth_img=None,
               out_size=(308,406),
               dense_landmarks=None
               ):
    crop_height = out_size[0]
    crop_width = out_size[1]

    # 6. Pad if needed to reach (crop_height, crop_width)
    p_top = p_bottom = p_left = p_right = 0
    final_img = img_cropped
    final_normals = normals_cropped

    if (img_cropped.shape[0] < crop_height) or (img_cropped.shape[1] < crop_width):
        # Pad image
        final_img, p_top, p_bottom, p_left, p_right = pad_width_or_height(
            img_cropped,
            output_width=crop_width,
            output_height=crop_height,
            return_offsets=True
        )
        # print(f"Padding offsets: top={p_top}, bottom={p_bottom}, left={p_left}, right={p_right}")

        # Pad normals_image in the same way (if present)
        if normals_cropped is not None:
            # We expect normals_cropped.shape == img_cropped.shape
            # So calling pad_width_or_height on normals_cropped yields same offsets
            final_normals, pt_n, pb_n, pl_n, pr_n = pad_width_or_height(
                normals_cropped,
                output_width=crop_width,
                output_height=crop_height,
                return_offsets=True
            )
            # Optionally, assert that offsets match:
            assert (pt_n == p_top and pb_n == p_bottom and
                    pl_n == p_left and pr_n == p_right), \
                "Padding offsets differ between img and normals_image!"

        if depth_img is not None:
            # Pad depth image in the same way
            depth_img, pt_d, pb_d, pl_d, pr_d = pad_width_or_height(
                depth_img,
                output_width=crop_width,
                output_height=crop_height,
                return_offsets=True
            )
            # Optionally, assert that offsets match:
            assert (pt_d == p_top and pb_d == p_bottom and
                    pl_d == p_left and pr_d == p_right), \
                "Padding offsets differ for depth image!"

    else:
        final_img = img_cropped
        final_normals = normals_cropped

    # 7. Adjust intrinsic matrix K if provided
    K_aug = None
    if K is not None:
        Ks = np.eye(3)
        Ks[0, 0] = 1
        Ks[1, 1] = 1

        Kc = np.eye(3)
        Kc[0, 2] = -1.0 * 0
        Kc[1, 2] = -1.0 * 0

        Kp = np.eye(3)
        Kp[0, 2] = float(p_left)
        Kp[1, 2] = float(p_top)

        K_aug = Kp.dot(Kc.dot(Ks.dot(K.copy())))

    if landmarks is not None:
        # Adjust landmarks for padding
        landmarks[:, 0] += p_left
        landmarks[:, 1] += p_top

    if dense_landmarks is not None:
        dense_landmarks[:, 0] += p_left
        dense_landmarks[:, 1] += p_top

    # 8. Build the result dictionary
    result = {
        'image': final_img,
        'normals_image': final_normals,
        'K':      K_aug,
        'landmarks': landmarks,
        'depth_img': depth_img,
        'dense_landmarks': dense_landmarks
    }
    return result
